name: 'Setup F´'
description: 'Setup the F´ repository and tools'
inputs:
  location:
    required: true
    default: $GITHUB_WORKSPACE
runs:
  using: "composite"
  steps:
  - run: git fetch --tags
    shell: bash
  - name: Add Python bin to PATH
    run: echo "/Library/Frameworks/Python.framework/Versions/Current/bin" >> $GITHUB_PATH
    shell: bash
  - run: |
      python3 -m venv "$(pwd)/fprime-venv"
      echo "$(pwd)/fprime-venv/bin" >> $GITHUB_PATH
    shell: bash
  - run: pip install -U -r ${{ inputs.location }}/requirements.txt
    shell: bash
  - run: which fprime-util
    shell: bash
  - run: which fprime-gds
    shell: bash
  - run: which fpp-check
    shell: bash
    
